id: A4B0F0D4E
base_file: fBC88.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:19:14.346841
  last_modified_at: 2022-06-15 20:19:14.346863
